### ISSUE TITLE
Encountering "ERROR: ICE expected slice sizes" for slice members

### ISSUE THREAD

**Issue by grasshopper47** [noir-lang/noir#3476]
## Set a slice-of-slices member property value

Consider the following structs:

```rust
struct Property
{
    key : [u8],
    value : [u8],
}

struct JSON
{
    doc : [Property]
}
```

Let's look at the snippet below. 

It does a linear search of `key` property bytes (`eq` is an extension method for `[u8]` provided privately), and looks to set/replace the `value` property bytes with a local `prop` instance bytes. 

```rust
let json = JSON { doc: [] };
let prop = Property { key: [], value:[] };

// .. parse json .. 

// .. set the property's key bytes .. 
// .. set the property's value bytes .. 

// add property to json or replace existing
let len : Field = json.doc.len();
let mut found = false;
for i in 0..len 
{ 
    if (!found) 
    { 
        if (prop.key.eq(json.doc[i].key)) 
        { 
            json.doc[i].value = prop.value; 
            found = true; 
        } 
    } 
}
```

This code worked fine until  **nightly-2023-11-04**. From this version onward the error "ICE expected slice sizes" is thrown by the compiler. This is confusing because it is missing contextual information.

The PR that lead to this breaking change is https://github.com/noir-lang/noir/commit/48cf1a7b15a838e928d774af6ab246f84fed2c78

A workaround is to refactor the code: create a copy of the `doc` property, skip the existing property, push the new property instance in the copy, then re-assign the copy to the initial json instance's `doc` property:

```rust
let mut copy : [Property] = [];
for current in json.doc { if (!prop.key.eq(current.key)) { copy = copy.push_back(current); } }
json.doc = copy.push_back(prop);
```

### Expected Behavior

The code provided should work as it did before **nightly-2023-11-04**

### Bug

1. Should work as before
2. The error should include more contextual information until 1 is fixed

### To Reproduce

See details in *Aim* section

### Installation Method

Binary

### Nargo Version

nargo 0.19.2

### Would you like to submit a PR for this Issue?

No

**Comment by vezenovm** [comment]
@grasshopper47 Do you have a more reproducible example? It would be helpful to see what your extension method `eq` is doing, as you shouldn't be able to declare impls on non-struct types unless you have it in your own version of the stdlib? 

Also in the provided snippet this should not be possible to compile to ACIR as the loop bound that comes from `let len : Field = json.doc.len();` is dynamic. I assume you are doing this in an unconstrained function?

I have this program here: 
```rust
struct Property
{
    key : [u8],
    value : [u8],
}

struct JSON
{
    doc : [Property]
}

unconstrained fn main() {
    let mut json = JSON { doc: [] };
    let mut prop = Property { key: [], value:[] };

    let other_prop = Property { key: [0, 1, 2], value:[10] };
    json.doc = json.doc.push_back(other_prop);

    for i in 0..3 {
        prop.key = prop.key.push_back(i as u8);
    }
    prop.value = prop.value.push_back(5);

    // add property to json or replace existing
    let len : Field = json.doc.len();
    let mut found = false;
    for i in 0..len 
    { 
        if (!found) 
        { 
            if (prop.key.eq(json.doc[i].key)) 
            { 
                json.doc[i].value = prop.value; 
                found = true; 
            } 
        } 
    }
    assert(found == true);
}
```
This program successfully executes following this PR (https://github.com/noir-lang/noir/pull/3617).

**Comment by vezenovm** [comment]
> This program successfully executes following this PR (#3617).

I have pulled this out into the PR here: https://github.com/noir-lang/noir/pull/3634.

**Comment by vezenovm** [comment]
@grasshopper47 Yes this is the issue, but this was only just merged into master. On the next nightly and release this should be fixed. The most recent nightly was published 16 hours ago. What version of nargo are you using? I just tested your simple example when building from source and it passes as expected.

**Comment by grasshopper47** [comment]
> @grasshopper47 Yes this is the issue, but this was only just merged into master. On the next nightly and release this should be fixed. The most recent nightly was published 16 hours ago. What version of nargo are you using? I just tested your simple example when building from source and it passes as expected.

I'm getting a bit confused; i thought the change went in via https://github.com/noir-lang/noir/pull/3634, which is already in `master`. I've built the latest `master`, with this change in, and the error still happens....

**Comment by vezenovm** [comment]
> I'm getting a bit confused; i thought the change went in via #3634, which is already in `master`. I've built the latest `master`, with this change in, and the error still happens....

When I build from `master` the error is gone. Are you using noirup to build from source?

**Comment by grasshopper47** [comment]
Previous comments "deleted"

**Comment by grasshopper47** [comment]
@vezenovm I'm re-reopening this

Still an issue, please run the code below and check the output
I've included printing to see the actual values in memory

```rust
global BEGIN_OBJECT    : u8 = 0x7B; // { left curly bracket
global END_OBJECT      : u8 = 0x7D; // } right curly bracket
global BACKSLASH       : u8 = 0x5C; // \ reverse solidus

global chars =
[
    "\0","\0","\0","\0","\0","\0","\0","\0","\0","\t","\n","\0","\0","\r","\0","\0","\0","\0","\0","\0","\0","\0","\0","\0","\0","\0","\0","\0","\0","\0","\0","\0",
    " ","!","\"","#","$","%","&","'","(",")","*","+",",","-",".","/",
    "0","1","2","3","4","5","6","7","8","9",
    ":",";","<","=",">","?","@",
    "A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T","U","V","W","X","Y","Z",
    "[","\\","]","^","_","`",
    "a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z",
    "{","|","}","~"
];

trait ByteArrayExtensions
{
    fn print(self);
}

struct Property
{
    key : [u8]
,   value : [u8]
}

type Object = [Property];

struct JSON
{
    doc : Object
}

impl<SIZE> ByteArrayExtensions for [u8; SIZE]
{
    unconstrained
    pub fn print(self)
    {
        dep::std::println("{");
        for byte in self { let c = chars[byte]; dep::std::println(f"    {c}"); }
        dep::std::println("}");
    }
}

impl Property
{
    unconstrained
    fn print(self)
    {
        dep::std::println(f"key");
        self.key.print();

        dep::std::println("value\n{");

        let mut object = false;
        for byte in self.value
        {
            if (object & (byte != END_OBJECT) & (byte != BACKSLASH))
            {
                dep::std::println(f"        {byte}");
            }
            else
            {
                let c = chars[byte];
                dep::std::println(f"    {c}");

                object = (byte == BEGIN_OBJECT);
            }
        }

        dep::std::println("}");
    }
}

impl JSON
{
    unconstrained
    fn store(mut self, prop : Property) -> Object
    {
        for i in 0..self.doc.len() { self.doc[i].value = prop.value; }

        self.doc
    }
}

#[test]
unconstrained
fn property_key_number_and_key_array_object()
{
    let mut json = JSON { doc: [ Property { key: "a".as_bytes(), value: "1".as_bytes() } ] };
    let mut prop = Property { key: "a".as_bytes(), value:"123".as_bytes() };

    json.doc = json.store(prop);

    for prop in json.doc { prop.print(); }
}
```

the output is:
```key
{
    1
    
    
    a
    1
    2
    3
    
    
    
    
    
    
    
    
}
value
{
    
}
```

not at all the expected key "a" and value "123" bytes

**Comment by grasshopper47** [comment]
If this works better as a separate issue, I can open a new one, just let me know what is preferred.

**Comment by vezenovm** [comment]
> If this works better as a separate issue, I can open a new one, just let me know what is preferred.

This is a separate bug so a new issue would be preferred.
